apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  initContainers:
  - name: init-myfile
    image: alpine:latest
    command: ['sh', '-c', 'apk add --no-cache wget && wget -O /data/myfile.txt https://raw.githubusercontent.com/BGLCorp/devops-interview-tests/refs/heads/main/myfile.txt?token=GHSAT0AAAAAADJRXY3RH2HHPFXQWLUI64UY2IHKYTQ']
    volumeMounts:
    - mountPath: /data
      name: temp

  containers:
  - name: myapp-container
    image: alpine:latest
    command: ['sh', '-c', 'cat /data/myfile.txt']
    volumeMounts:
    - mountPath: /data
      name: temp

  volumes:
  - emptyDir: {}
    name: temp